### ISSUE TITLE
Editorial rules: super- and sub-script in conjunction with musical note names / also use of italics in enumeration

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#12]
I simply would like to ask for some feedback regarding my transcription choices with these symbols from "Ideen zu einer Lehre der Tonvorstellungen", page 25. In brackets, the author enumerates a series of notes. See the screenshot for my solutions.

![Issue 7-1-21](https://user-images.githubusercontent.com/75686579/104027751-215d3e00-51c8-11eb-8c2f-823bfff3e00e.png)

Some of the choices I have made here are:

1. to use super- and subscript for each of the 3-, 2-, - type symbols. Meaning that for consistency's sake, "_f" is always represented as "-f", but with the "-" being subscript", as opposed to a normal underscore.
2. to ignore arbitrary spacing in the edition. For some reason, there are two spaces within the last two elements in the first bracket, which do not reappear in the other ones. I interpret this as a mistake in the edition.
3. to set the entire thing as cursive, rather than each of the elements separately. <- This one is the one I am least sure about. Maybe it's more accurate to not set the commas cursive?

**Comment by fabianmoss** [comment]
1. great choice, I think this is how it should be done. Please make a note in the [Editorial decisions](https://github.com/DCMLab/ddd/wiki/Editorial-decisions) with a reference to the page or include this screenshot
2. yes, we should do it like this
3. Also yes, the entire symbol should be cursive. However, the commas should not be since they are just separators of the "things" and thus normal text.

**Comment by m-k94** [comment]
Thank you, I fixed the commas accordingly and added a new part to the Editorial decisions document. Please check if the wording is okay or whether an image should be added. I have chosen to just refer to the page since the image was very large.
