### ISSUE TITLE
Spelling mistakes on images - to correct or to leave?

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#19]
For my current document of Riemann, the OCR is usually very accurate aside from some minor reoccurring issues. When I do notice a mistake, it is often actually not a transcription error, but an error in the image. Take for instance the misspelling of "Auflösungszeichen" into "Auflösungszeiehen":

![Auflösungszeiehen](https://user-images.githubusercontent.com/75686579/104224170-e3208280-5444-11eb-8983-c2394b15bb44.png)

Should we tacitly fix such obvious typos, or keep them? So far, I have transcribed them as they are in the image and tagged them as "sic".

**Comment by m-k94** [comment]
I have the suspicion that the mistakes in this edition are themselves a product of some sort of OCR, if such a technology was available in 1999. It has typical OCR mistakes such as "m = in" or "rn = m".

**Comment by fabianmoss** [comment]
Your suspicion makes sense to me. In such cases of obvious errors, you can correct them (please note that in the Wiki, too). What we don't correct are old spellings of words.

**Comment by m-k94** [comment]
Does the same apply to punctuation errors in historical sources? I'm talking about cases that are simply _wrong_, not just outdated.

Hauptmann p. 15 has the following sentence:

![image](https://user-images.githubusercontent.com/75686579/104336724-030f7f00-54f5-11eb-9cf1-eab269a20ae5.png)

Clearly, the full stop after "Verdoppelungen" was intended to be a comma, as it doesn't make any grammatical sense.

**Comment by fabianmoss** [comment]
I think in this case, the error happened in the scanning process (the tiny dot below the period seems to be the continuation of the actual comma). So here a comma would be mandatory.

If you should encounter a situation where there is clearly a wrong punctuation, we should correct it in order to enable, for example, splitting the text into sentences automatically. But I assume that these cases will occur extremely rarely, if at all.
