### ISSUE TITLE
Hauptmann - Long line at the end of paragraph = "Geviertstrich"?

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#21]
Tiny editorial question: 

![image](https://user-images.githubusercontent.com/75686579/104335871-19690b00-54f4-11eb-8772-4b7ff4b2f0f8.png)

The line at the end of the paragraph should just be transcribed as a "long dash" (Geviertstrich), shouldn't it? By the way, similar to some of the unicode symbols, the line appears to be flipped by 90 degrees in the transcription box, even when you insert it through Transkribus' "insert a long dash" button at the bottom left - so it's probably correct, just displayed wrong.

**Comment by fabianmoss** [comment]
It seems like a long dash. Could you post the page number so I can check?
Yes, Transkribus displays it as "|". Don't be confused. It will be exported correctly. I think they just do it so you can enter it more quickly and directly from the keyboard without having to use the mouse.

**Comment by m-k94** [comment]
Oh sorry, I forgot to mention the page: it's page 15.

**Comment by fabianmoss** [comment]
This is an interesting case. The long dash just seems to emphasize that this paragraph has ended, since a new one starts on the next line. Other than that, it has no syntactical function (meaning, nothing would change if we omitted it). 

Hauptmann seems to do this occasionally, e.g. at the end of a paragraph (and section) on p. 53, as well as at the beginning of a paragraph on p. 52. Let's keep them and transcribe them as "|".

**Comment by m-k94** [comment]
Yes, he does use it as a stronger end to a paragraph. I agree with keeping it as a long dash.
