### ISSUE TITLE
Must baselines and transcription lines match one another?

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#26]
Is it bad when the transcribed lines relate to the wrong baselines? (Assuming the transcription is still correct in itself, of course)

I had such a case on a page in Riemann's "Ideen zu einer Lehre": Because the line segmentation was broken. I transcribed the lines by hand, but they still are still related to the wrong baselines (see issue #15).

Now I see a page which I believe you, Fabian, have worked on in Riemann 1880. (p. 8) After line 3-2, which has no baseline associated with it, it starts being "out of synch" with Transkribus' baselines: When clicking on any text line, the line _above_ it is highlighted on the image. 

![image](https://user-images.githubusercontent.com/75686579/104749479-27689700-5753-11eb-9589-451148617b12.png)

Are such things a problem for us? I suppose it would be cleanest to make sure everything aligns, but it would also take more time. I think this might be an important question to discuss!

**Comment by fabianmoss** [comment]
Let's talk about this at our next meeting. Generally, you are right that it would be best if everything were perfectly aligned. 
My feeling is that it is worth the time to adjust that always. Otherwise we might get problems when we export it to XML because, e.g. the order of the lines might get messed up.
