### ISSUE TITLE
Editorial rule: "" or actual quotation marks

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#35]
One of the most basic and common questions in editorial guidelines is what kinds of quotation marks to use, i.e. whether to use the simple " ones found on the keyboard, or more proper quotation marks such as either of these: `❝ ❞ ❛ ❜ ‘ ’ ‛ ‚ “ ” „ ‟ « » ‹ ›`.

Transkribus does sometimes transcribe them as actual, asymmetrical quotation marks, but like the 'long dashes', they get displayed in a weird way in the text, appearing on the bottom at the line. See this page, for instance:

![image](https://user-images.githubusercontent.com/75686579/105925950-4b748400-6041-11eb-8b68-79d0a5112964.png)
(this is Kunkel, p. 6)

In the past weeks I have often replaced them with "" type marks, because I assumed it to be a mistake, but I reckon it's probably the correct symbol. Still, I'd like us to clarify when we use which type of quotation mark. The proper, asymmetrical ones are nice, but not as easy to type. Also, when the text uses "french" type quotation marks. (« »), I suppose we have to use them too in transcription?

**Comment by fabianmoss** [comment]
In this case, we can take a clear editorial decision (to be recorded in the guidelines ;-) ): Since our main goal is not to reproduce the original sources as closely as possible, we can "modernize" punctuation (as we did also for other punctuation signs, like the hyphen "-" instead of "=") and use the modern German version of Quotation marks (like the ones shown in the image above) for all double quotations.
