### ISSUE TITLE
Single line above Music example: is it a Caption or paragraph?

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#61]
![image](https://user-images.githubusercontent.com/75686579/112991042-00710d00-9167-11eb-90ce-e045b365f823.png)

I find this a bit strange. On one hand, the indentation makes it look like it's part of a paragraph, as does the semicolon at the end of this line. On the other hand, the paragraph does not continue and it might as well be a heading for the music. Currently it is marked up as paragraph but I am not sure if it should better be "caption" or just merged with the music.

**Comment by fabianmoss** [comment]
Yes, strange indeed. I think that's not a case we'll have often and would suggest to treat it as a paragraph. I think the structural meaning is that the music example is in line, so we have a one-line paragraph where the music example follows the line break.

On another note: His terminology for fourths is really weird. The "kleine Quarte" is a perfect one, and I don't see a difference between a "große" and a "übermäßige Quarte". Or are these examples for "unrichtige Benennungen"?

**Comment by fabianmoss** [comment]
Yes that's what he wants to do, I guess. But it doesn't make sense, since he acknowledges that major and minor intervals are inversionally related, as well as augmented and diminished. So he basically replaces (only for the fourth apparently) "augmented fourth" with "major fourth" and "diminished fourth" with "minor fourth". Strange... But not our concern right now ;-)

**Comment by m-k94** [comment]
Indeed!
